name: Update Pacman Animation
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Pacman
        uses: JasonEtco/activity-box@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit files
        run: |
          git config --global user.name "Shreya-196"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "Update Pacman animation"
          git push
